language: cpp
os:
- linux
- osx
- windows
addons:
  apt:
    packages:
    - libluajit-5.1-dev
    - libluajit-5.1-dev:i386
    - g++-multilib
filter_secrets: false
install:
- curl -u yancouto:$SDK_TOKEN -sL https://raw.githubusercontent.com/yancouto/private-steamworks-sdk/master/steamworks_sdk_151.zip
  -o sdk.zip
- unzip -q sdk.zip
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y visualstudio2017-workload-vctools; fi
script:
- mkdir build
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then     make osx               && mv luasteam.so  build/osx_luasteam.so;     fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make linux64           && cp luasteam.so  build/linux64_luasteam.so; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   make linux32           && cp luasteam.so  build/linux32_luasteam.so; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mingw32-make windows64 && cp luasteam.dll build/win64_luasteam.dll;  fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then mingw32-make windows32 && cp luasteam.dll build/win32_luasteam.dll;  fi
deploy:
  provider: releases
  api_key:
    secure: GNS5tPvu63Y+viY3WeRchr1EUpUZi273XhRgjCfMrY3rzPS1UKW2FYcop2EWtxxxmtupV9G80m3az1RAkmbs+J7HeLSYX1iOe3sD+TsKM8KYuoalHAb82w5LV/C/w0Kgt1CQlVaWy/Yp47KoZ2vNr/61Q1PNu5BErA6Y4GLLYtd+ivbYOakTkUIBRCtntgoWXKqu9DW1bY+CzysvSSjsgajJZSx/in7fY1p5Zslyp+v13NDixOJ2DVkcLa2pByf560symkVqKRktaY3xtSPh4x0ya0nkunEvHdr1rQVyZVvvXykL3tn3EFyqeVyBCKLR5kgoZ/YDqvX/A5LEVIfS4DVC4VtoLo77GUE3brPq8v230Z2TOGViPCGUj3HxSF1CSYU45oIj91AD5HAOXQq56VtNPUpJ9KXbGA/EKqKqPHNhUwGo+G7Us0j8TeMHU0sIluk9NBp4xE+aC3yVbPgbXAGIh4bk2kztV5kg/Udu3Pt0gael8av5SN3xAVbvC4ZaeW3L6Yl/opOmR7HMp3RUiK4MU8mkfkrYH3D/t7Qd61CAEkJHnMM0Jo8u9C+rzN41JZ+Y7VUfuv1P0zIXKxdLZKxng1IgH3Ml5YpOaePC+tJgJcXKFsOPMurGQ5ha5sjKVWz49TNOPnCVQVkckPgvQhUkrImMHE8ExdObUqvw7DQ=
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
    repo: uspgamedev/luasteam
